//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WaterLevelIndicator.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StationNames
    {
        public int Station_ID { get; set; }
        public string Station_Name { get; set; }
    }
}
